name: Build Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - dev

jobs:
    build-check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            # Install Dependencies
            - name: Install Dependencies
              run: yarn install

            # Astro Type Check 
            - name: Astro Check
              run: yarn astro check

            # Astro Build
            - name: Astro Build
              run: yarn astro build
