name: Build Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
            - dev

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            # Astro Type Check 
            - name: Astro Check
              run: astro check

            # Astro Build
            - name: Astro Build
              run: astro build
